package com.github.sommeri.less4j.core.output;

import com.github.sommeri.less4j.core.parser.HiddenTokenAwareTree;
import com.github.sommeri.sourcemap.SourceMapGenerator;

public interface ISourceMapBuilder {

  public void appendAsSymbol(String str, HiddenTokenAwareTree underlyingStructure);

  public void append(ISourceMapBuilder other);

  public String toSourceMap();
  
  /**
   * Leaky abstraction: I could have create abstraction over Mappings generated by 
   * generator (that is what I really need), but since this is not an API and is used 
   * only internally such thing would be overkill.  
   */
  public SourceMapGenerator getInternalGenerator();

  //FIXME: source map: clean up once it works
  public ExtendedStringBuilder getCssBuilder();

}